# -*- coding: utf-8 -*-

"""OMVT vision-tower self-supervised pretraining entry point.

Runs the four SSL heads (OCR reconstruction, masked patch, orientation,
layout order) on synthetic batches by default. Pass ``--data <jsonl>``
to drive the loop from real images:

* orientation labels are self-generated by random 0/90/180/270 rotation;
* OCR loss is only computed when the row carries ``ocr_labels`` (gracefully
  skipped otherwise, ``w_ocr`` effectively dropped to zero for that step);
* layout-order targets come from the row's ``reading_order`` when present,
  falling back to ``arange`` so existing SSL signal is preserved.
"""

from __future__ import annotations

import argparse
import json
import os
import queue
import random
import shutil
import threading
import time
from dataclasses import asdict
from pathlib import Path
from typing import Iterator

import torch

from Model.config import OMVTConfig
from Model.omvt import (
    LayoutOrderHead,
    MaskedPatchHead,
    OCRReconstructionHead,
    OMVTVisionTower,
    OrientationHead,
    collate_omvt_batch,
    layout_order_loss,
    masked_patch_loss,
    ocr_reconstruction_loss,
    orientation_loss,
)
from Model.training import RankZeroLogger, build_optimizer, clip_or_check_grad_norm
from Model.training.optim import build_scheduler
from Model.training.multimodal_cli import make_omvt_cfg
from Model.training.omvt_checkpoint import resolve_omvt_checkpoint_path
from Model.config import TrainingConfig
from Tokenizer.multimodal import PILImageProcessor


def parse_args(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--steps", type=int, default=4)
    p.add_argument("--batch-size", type=int, default=2)
    p.add_argument("--image-size", type=int, default=56)
    p.add_argument("--d-vision", type=int, default=64)
    p.add_argument("--compress-to", type=int, default=8)
    p.add_argument("--ocr-vocab", type=int, default=64)
    p.add_argument(
        "--data",
        default="",
        help="JSONL path with rows {'images': [...], 'ocr_labels': [...], 'reading_order': [...]} "
        "(ocr_labels / reading_order optional)",
    )
    p.add_argument(
        "--pair-shards-dir",
        default="",
        help="directory with pre-rendered WebDataset shard-NNNNN.tar pairs",
    )
    p.add_argument(
        "--pair-shard-indices",
        default="",
        help="shard index spec for --pair-shards-dir, e.g. 0:3479",
    )
    p.add_argument(
        "--tokenizer-bundle",
        default="",
        help="TokenizerBundle directory required for --pair-shards-dir",
    )
    p.add_argument("--pair-max-seq-len", type=int, default=512)
    p.add_argument("--pair-val-src-doc-min", type=int, default=434600)
    p.add_argument("--pair-test-src-doc-min", type=int, default=435200)
    p.add_argument("--output", default="outputs/omvt_ssl")
    p.add_argument("--resume", default="")
    p.add_argument("--save-every", type=int, default=0)
    p.add_argument("--smoke", action="store_true")
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument(
        "--patch-preset",
        choices=("derived", "prod"),
        default="derived",
        help="'derived' keeps the legacy smoke geometry (patches scaled from "
        "--image-size); 'prod' uses the OMVTConfig dataclass multi-scale "
        "defaults (32x8 / 8x32 / 16x16 / 56x56), intended for real pages.",
    )
    p.add_argument(
        "--device",
        choices=("auto", "cpu", "cuda", "mps"),
        default="auto",
        help="'auto' = cuda if available else cpu (legacy behavior)",
    )
    p.add_argument(
        "--precision",
        choices=("auto", "fp32", "bf16"),
        default="auto",
        help="'auto' = bf16 on cuda, fp32 elsewhere",
    )
    p.add_argument("--warmup-steps", type=int, default=200)
    p.add_argument(
        "--lr-decay-steps",
        type=int,
        default=None,
        help="LR schedule horizon; defaults to --steps",
    )
    p.add_argument(
        "--ema-decay", type=float, default=0.999,
        help="EMA decay for the tower weights (0 disables); the EMA tower is "
        "saved as 'tower_ema' in checkpoints and preferred by eval",
    )
    p.add_argument(
        "--crop-prob", type=float, default=0.0,
        help="probability of replacing a page with a random square crop "
        "(glyph-scale augmentation). Cropped rows train without OCR labels.",
    )
    p.add_argument("--crop-min", type=float, default=0.30,
                   help="min crop side as a fraction of the short page side")
    p.add_argument("--crop-max", type=float, default=0.60)
    p.add_argument("--prefetch", type=int, default=4,
                   help="batches prepared ahead by a loader thread (0 = off)")
    return p.parse_args(argv)


def _omvt_cfg(args) -> OMVTConfig:
    return make_omvt_cfg(
        args.image_size,
        args.d_vision,
        args.compress_to,
        preset=getattr(args, "patch_preset", "derived"),
    )


def _training_cfg(args, cfg: OMVTConfig, use_bf16: bool) -> TrainingConfig:
    return TrainingConfig(
        train_data="",
        seq_len=cfg.compress_to,
        micro_batch_size=args.batch_size,
        learning_rate=args.lr,
        weight_decay=0.05,
        max_steps=args.steps,
        warmup_steps=max(1, args.warmup_steps),
        lr_decay_steps=args.lr_decay_steps,
        precision="bf16" if use_bf16 else "fp32",
    )


def _first_seq(value: object) -> list[int] | None:
    """Normalize a schema-correct ``list[list[int]]`` field to a 1-D row.

    The multimodal JSONL schema stores ``ocr_labels`` / ``reading_order``
    as one sequence per image (``[[id, id, ...], ...]``). The SSL trainer
    operates on one image per row, so we pick the first image's sequence
    and return ``None`` when it is missing or empty.
    """

    if not value:
        return None
    head = value[0] if isinstance(value, (list, tuple)) else None
    if isinstance(head, (list, tuple)):
        return [int(x) for x in head] or None
    if isinstance(head, int):
        # Legacy or hand-built rows that already store a flat list.
        return [int(x) for x in value]  # type: ignore[arg-type]
    return None


def _iter_pair_shards(
    shards_dir: str,
    shard_indices: list[int],
    batch_size: int,
    image_processor: PILImageProcessor,
    encode_target,
    *,
    seed: int,
    n_image_tokens: int,
    max_seq_len: int = 512,
    val_src_doc_min: int = 434600,
    test_src_doc_min: int = 435200,
    crop_prob: float = 0.0,
    crop_min: float = 0.30,
    crop_max: float = 0.60,
) -> Iterator[dict]:
    """Yield SSL batches directly from WebDataset-style tar shards.

    This streams the NAS image-text corpus without materializing a second
    224x224 copy on disk. It mirrors ``build_ocr_data_from_pairs``: keep only
    train-band ``kind=="line"`` rows, byte-fallback encode targets, skip
    over-length rows, and letterbox source strips before train-time image
    processing.
    """

    if not shard_indices:
        raise ValueError("pair shard indices must not be empty")
    if val_src_doc_min >= test_src_doc_min:
        raise ValueError("pair val src_doc min must be < test src_doc min")

    from scripts.build_ocr_data_from_pairs import (
        ShardCounters,
        iter_tar_pairs,
        letterbox_to_square,
        shard_path,
    )

    rng = torch.Generator().manual_seed(seed)
    pyrng = random.Random(seed)
    prompt_overhead = 4 + int(n_image_tokens)

    while True:
        imgs: list = []
        ocr: list = []
        for shard_index in shard_indices:
            tar_path = shard_path(shards_dir, shard_index)
            counters = ShardCounters(shard_index)
            for key, png_bytes, row in iter_tar_pairs(tar_path, counters):
                if row.get("kind") != "line":
                    continue
                src_doc = row.get("src_doc")
                if not isinstance(src_doc, int):
                    raise ValueError(f"{tar_path}: key={key!r}: invalid src_doc")
                if src_doc >= val_src_doc_min:
                    continue
                text = row.get("text")
                if not isinstance(text, str) or not text:
                    raise ValueError(f"{tar_path}: key={key!r}: missing text")
                target_ids = encode_target(text)
                if max_seq_len > 0 and prompt_overhead + len(target_ids) > max_seq_len:
                    continue

                spec = letterbox_to_square(png_bytes, image_processor.image_size)
                label = target_ids
                if crop_prob > 0 and pyrng.random() < crop_prob:
                    short = min(spec.size)
                    side = max(32, int(short * pyrng.uniform(crop_min, crop_max)))
                    x = pyrng.randint(0, max(spec.width - side, 0))
                    y = pyrng.randint(0, max(spec.height - side, 0))
                    spec = spec.crop((x, y, x + side, y + side))
                    label = None

                imgs.append(spec)
                ocr.append(label)
                if len(imgs) == batch_size:
                    yield {
                        "images": image_processor(imgs),
                        "ocr_labels": ocr,
                        "reading_order": [None] * batch_size,
                        "rng": rng,
                    }
                    imgs = []
                    ocr = []


def _iter_real_jsonl(
    path: str,
    batch_size: int,
    image_processor: PILImageProcessor,
    *,
    seed: int,
    crop_prob: float = 0.0,
    crop_min: float = 0.30,
    crop_max: float = 0.60,
) -> Iterator[dict]:
    """Yield batched real-image samples from a JSONL spec.

    Each yielded dict carries ``images`` ``[B,C,H,W]`` plus the optional
    ``ocr_labels`` / ``reading_order`` lists (``None`` when no row in the
    micro-batch supplies them). The iterator wraps around forever so the
    caller controls termination via ``--steps``.

    With ``crop_prob`` > 0 a row is sometimes replaced by a random square
    crop of its page: at full-page resolution individual glyphs are only a
    few pixels tall, so crops are what teach the tower glyph-scale detail.
    A crop is no longer described by the page's transcription, so its OCR
    label is dropped (the trainer already trains label-free rows).
    """

    rng = torch.Generator().manual_seed(seed)
    pyrng = random.Random(seed)
    while True:
        with open(path, "r", encoding="utf-8") as fh:
            buf: list[dict] = []
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                row = json.loads(line)
                if not row.get("images"):
                    continue
                buf.append(row)
                if len(buf) < batch_size:
                    continue
                imgs: list = []
                ocr: list = []
                for row in buf:
                    spec = row["images"][0]
                    label = _first_seq(row.get("ocr_labels"))
                    if crop_prob > 0 and pyrng.random() < crop_prob:
                        from PIL import Image as _Image

                        img = _Image.open(spec)
                        img.load()
                        short = min(img.size)
                        side = max(32, int(short * pyrng.uniform(crop_min, crop_max)))
                        x = pyrng.randint(0, max(img.width - side, 0))
                        y = pyrng.randint(0, max(img.height - side, 0))
                        spec = img.crop((x, y, x + side, y + side))
                        label = None
                    imgs.append(spec)
                    ocr.append(label)
                stacked = image_processor(imgs)
                ro = [_first_seq(row.get("reading_order")) for row in buf]
                yield {
                    "images": stacked,
                    "ocr_labels": ocr,
                    "reading_order": ro,
                    "rng": rng,
                }
                buf = []


def _prefetch(it: Iterator[dict], depth: int) -> Iterator[dict]:
    """Run ``it`` in a daemon thread, keeping up to ``depth`` batches ready.

    Image decode + resize is otherwise serialized with the optimizer step;
    on GPU runs that data starvation was measured to cost ~40% wall clock.
    """

    if depth <= 0:
        yield from it
        return
    q: "queue.Queue" = queue.Queue(maxsize=depth)
    _END = object()

    def _fill() -> None:
        try:
            for item in it:
                q.put(item)
            q.put(_END)
        except BaseException as exc:  # propagate loader crashes to the main loop
            q.put(exc)

    threading.Thread(target=_fill, daemon=True, name="ssl-prefetch").start()
    while True:
        item = q.get()
        if item is _END:
            return
        if isinstance(item, BaseException):
            raise item
        yield item


class _Ema:
    """Exponential moving average of a module's floating-point state."""

    def __init__(self, module: torch.nn.Module, decay: float) -> None:
        self.decay = float(decay)
        self.shadow = {
            k: v.detach().clone()
            for k, v in module.state_dict().items()
            if v.dtype.is_floating_point
        }

    @torch.no_grad()
    def update(self, module: torch.nn.Module) -> None:
        for k, v in module.state_dict().items():
            if k in self.shadow:
                self.shadow[k].mul_(self.decay).add_(
                    v.detach(), alpha=1.0 - self.decay
                )


def _rotate_batch(images: torch.Tensor, labels: torch.Tensor) -> torch.Tensor:
    """Apply per-sample 0/90/180/270 rotations matching the orientation labels."""

    out = torch.empty_like(images)
    for i, k in enumerate(labels.tolist()):
        out[i] = torch.rot90(images[i], k=int(k), dims=(1, 2))
    return out


def _masked_patch_step(
    tower: OMVTVisionTower,
    mp_head: MaskedPatchHead,
    images: torch.Tensor,
    cfg: OMVTConfig,
) -> torch.Tensor:
    """Real masked-image-modeling loss on the square-patch stream.

    A random ``mask_ratio`` fraction of square patches is zeroed *before*
    encoding; the head must reconstruct the original pixels of those hidden
    patches from the (position-aware) encoder output. Loss is scored only on
    masked positions — this is a genuine SSL signal, unlike regressing onto
    random noise.
    """

    batch = collate_omvt_batch(images, cfg)
    target = batch["square_patches"]  # [B, n_patches, patch_pixels]
    bbox = batch["square_bbox"]
    bsz, n_patches, _ = target.shape

    mask = torch.rand(bsz, n_patches, device=target.device) < cfg.mask_ratio
    # Guarantee at least one masked patch per row so every sample contributes.
    none_masked = ~mask.any(dim=1)
    if bool(none_masked.any()):
        forced = torch.randint(0, n_patches, (int(none_masked.sum()),), device=target.device)
        mask[none_masked, forced] = True

    masked_in = target.clone()
    masked_in[mask] = 0.0
    feats = tower.encoders["square"](masked_in, bbox)  # [B, n_patches, d_vision]
    predicted = mp_head(feats)  # [B, n_patches, patch_pixels]
    return masked_patch_loss(predicted, target, mask=mask)


def _save_checkpoint(
    output: str | Path,
    step: int,
    cfg: OMVTConfig,
    tower: OMVTVisionTower,
    ocr_head: OCRReconstructionHead,
    mp_head: MaskedPatchHead,
    ori_head: OrientationHead,
    layout_head: LayoutOrderHead,
    optimizer: torch.optim.Optimizer,
    ema: "_Ema | None" = None,
) -> Path:
    out = Path(output)
    step_dir = out / f"step_{step:08d}"
    step_dir.mkdir(parents=True, exist_ok=True)
    payload = {
        "step": int(step),
        "omvt_config": asdict(cfg),
        "tower": tower.state_dict(),
        "ocr_head": ocr_head.state_dict(),
        "masked_patch_head": mp_head.state_dict(),
        "orientation_head": ori_head.state_dict(),
        "layout_head": layout_head.state_dict(),
        "optimizer": optimizer.state_dict(),
    }
    if ema is not None:
        payload["tower_ema"] = ema.shadow
    torch.save(
        payload,
        step_dir / "omvt_ssl.pt",
    )
    latest = out / "latest"
    if latest.exists() or latest.is_symlink():
        try:
            latest.unlink()
        except OSError:
            shutil.rmtree(latest, ignore_errors=True)
    try:
        os.symlink(step_dir.name, latest)
    except OSError:
        # Some filesystems disallow symlinks; the step dir remains valid.
        pass
    return step_dir


def _load_checkpoint(
    path: str | Path,
    tower: OMVTVisionTower,
    ocr_head: OCRReconstructionHead,
    mp_head: MaskedPatchHead,
    ori_head: OrientationHead,
    layout_head: LayoutOrderHead,
    optimizer: torch.optim.Optimizer | None = None,
) -> int:
    payload = torch.load(
        resolve_omvt_checkpoint_path(path),
        map_location="cpu",
        weights_only=False,
    )
    tower.load_state_dict(payload["tower"])
    ocr_head.load_state_dict(payload["ocr_head"])
    mp_head.load_state_dict(payload["masked_patch_head"])
    ori_head.load_state_dict(payload["orientation_head"])
    layout_head.load_state_dict(payload["layout_head"])
    if optimizer is not None and payload.get("optimizer") is not None:
        optimizer.load_state_dict(payload["optimizer"])
    return int(payload.get("step", 0))


def main(argv=None):
    args = parse_args(argv)
    pair_mode = bool(args.pair_shards_dir or args.pair_shard_indices)
    if args.data and pair_mode:
        raise ValueError("--data and --pair-shards-dir are mutually exclusive")
    if pair_mode and not (
        args.pair_shards_dir and args.pair_shard_indices and args.tokenizer_bundle
    ):
        raise ValueError(
            "--pair-shards-dir requires --pair-shard-indices and --tokenizer-bundle"
        )
    torch.manual_seed(args.seed)
    if getattr(args, "device", "auto") == "auto":
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(args.device)

    cfg = _omvt_cfg(args)
    tower = OMVTVisionTower(cfg).to(device)
    ocr_head = OCRReconstructionHead(cfg.d_vision, args.ocr_vocab).to(device)
    mp_head = MaskedPatchHead(cfg.d_vision, patch_pixels=cfg.square_patch[0] * cfg.square_patch[1] * cfg.in_channels).to(device)
    ori_head = OrientationHead(cfg.d_vision).to(device)
    layout_head = LayoutOrderHead(cfg.d_vision, max_positions=cfg.compress_to).to(device)

    modules = torch.nn.ModuleList([tower, ocr_head, mp_head, ori_head, layout_head])
    use_bf16 = args.precision == "bf16" or (
        args.precision == "auto" and device.type == "cuda"
    )
    train_cfg = _training_cfg(args, cfg, use_bf16)
    optimizer = build_optimizer(modules, train_cfg)
    scheduler = build_scheduler(optimizer, train_cfg)
    ema = _Ema(tower, args.ema_decay) if args.ema_decay > 0 else None
    start_step = 0
    if args.resume:
        start_step = _load_checkpoint(
            args.resume,
            tower,
            ocr_head,
            mp_head,
            ori_head,
            layout_head,
            optimizer,
        )
        for _ in range(start_step):
            scheduler.step()
        if ema is not None:
            # Re-seed the EMA from the restored tower; close enough after a
            # few hundred steps and avoids a checkpoint format dependency.
            ema = _Ema(tower, args.ema_decay)

    Path(args.output).mkdir(parents=True, exist_ok=True)
    logger = RankZeroLogger(args.output, enable_tensorboard=False)

    t0 = time.time()
    real_iter = None
    if args.data:
        real_iter = _prefetch(
            _iter_real_jsonl(
                args.data,
                args.batch_size,
                PILImageProcessor(image_size=args.image_size),
                seed=args.seed,
                crop_prob=args.crop_prob,
                crop_min=args.crop_min,
                crop_max=args.crop_max,
            ),
            args.prefetch,
        )
    elif pair_mode:
        from Tokenizer.unified.bundle import TokenizerBundle
        from scripts.build_ocr_data import make_ocr_target_encoder
        from scripts.build_ocr_data_from_pairs import parse_shard_indices

        bundle = TokenizerBundle.from_dir(args.tokenizer_bundle)
        encode_target = make_ocr_target_encoder(bundle.tokenizer)
        real_iter = _prefetch(
            _iter_pair_shards(
                args.pair_shards_dir,
                parse_shard_indices(args.pair_shard_indices),
                args.batch_size,
                PILImageProcessor(image_size=args.image_size),
                encode_target,
                seed=args.seed,
                n_image_tokens=cfg.compress_to,
                max_seq_len=args.pair_max_seq_len,
                val_src_doc_min=args.pair_val_src_doc_min,
                test_src_doc_min=args.pair_test_src_doc_min,
                crop_prob=args.crop_prob,
                crop_min=args.crop_min,
                crop_max=args.crop_max,
            ),
            args.prefetch,
        )

    last_step = start_step
    for step in range(start_step + 1, args.steps + 1):
        last_step = step
        if real_iter is None:
            images = torch.randn(args.batch_size, cfg.in_channels, cfg.image_size, cfg.image_size, device=device)
            ocr_labels_real: list | None = None
            ro_real: list | None = None
        else:
            sample = next(real_iter)
            # Orientation: self-generated label from random rotation —
            # this is the canonical 4-way rotation SSL task.
            ori_labels = torch.randint(0, 4, (args.batch_size,), generator=sample["rng"])
            images = _rotate_batch(sample["images"], ori_labels).to(device)
            ocr_labels_real = sample["ocr_labels"]
            ro_real = sample["reading_order"]

        with torch.autocast(
            device_type=device.type, dtype=torch.bfloat16, enabled=use_bf16
        ):
            feats = tower(images)["compressed"]  # [B, compress_to, d_vision]
        # The OCR/orientation/layout heads and their CE losses run fp32: they
        # are tiny, and CE in bf16 buys nothing but noise.
        feats = feats.float()

        ocr_logits = ocr_head(feats)
        if real_iter is None or all(x is None for x in (ocr_labels_real or [])):
            # Synthetic OCR signal (smoke path) or row carries no OCR
            # label: fabricate random targets so the head still trains.
            ocr_labels = torch.randint(0, args.ocr_vocab, (args.batch_size, cfg.compress_to), device=device)
            loss_ocr = ocr_reconstruction_loss(ocr_logits, ocr_labels)
            w_ocr = cfg.w_ocr if real_iter is None else 0.0
        else:
            padded = torch.full((args.batch_size, cfg.compress_to), -100, dtype=torch.long, device=device)
            for i, lab in enumerate(ocr_labels_real):
                if not lab:
                    continue
                lab_t = torch.tensor(lab[: cfg.compress_to], dtype=torch.long, device=device)
                padded[i, : lab_t.numel()] = lab_t
            loss_ocr = ocr_reconstruction_loss(ocr_logits, padded)
            w_ocr = cfg.w_ocr

        # The masked-patch step is dominated by its own square-encoder
        # forward, so the whole step (head included) runs under autocast like
        # the main tower pass; mse_loss is autocast-promoted back to fp32.
        with torch.autocast(
            device_type=device.type, dtype=torch.bfloat16, enabled=use_bf16
        ):
            loss_mp = _masked_patch_step(tower, mp_head, images, cfg).float()

        ori_logits = ori_head(feats)
        if real_iter is None:
            ori_labels = torch.randint(0, 4, (args.batch_size,), device=device)
        else:
            ori_labels = ori_labels.to(device)
        loss_ori = orientation_loss(ori_logits, ori_labels)

        layout_logits = layout_head(feats)
        if real_iter is None or all(x is None for x in (ro_real or [])):
            layout_targets = torch.arange(cfg.compress_to, device=device).unsqueeze(0).expand(args.batch_size, -1)
        else:
            layout_targets = torch.zeros(args.batch_size, cfg.compress_to, dtype=torch.long, device=device)
            base = torch.arange(cfg.compress_to)
            for i, ro in enumerate(ro_real):
                seq = torch.tensor(ro[: cfg.compress_to], dtype=torch.long) if ro else base
                layout_targets[i, : seq.numel()] = seq.to(device)
                if seq.numel() < cfg.compress_to:
                    layout_targets[i, seq.numel():] = base[seq.numel():].to(device)
        loss_layout = layout_order_loss(layout_logits, layout_targets)

        loss = (
            w_ocr * loss_ocr
            + cfg.w_masked_patch * loss_mp
            + cfg.w_orientation * loss_ori
            + cfg.w_layout_order * loss_layout
        )
        if not bool(torch.isfinite(loss.detach())):
            raise FloatingPointError(f"non-finite OMVT SSL loss at step {step}")
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        clip_or_check_grad_norm(modules, 1.0, step=step)
        optimizer.step()
        scheduler.step()
        if ema is not None:
            ema.update(tower)

        logger.log(step, {
            "loss": float(loss.detach()),
            "ocr": float(loss_ocr.detach()),
            "mp": float(loss_mp.detach()),
            "ori": float(loss_ori.detach()),
            "layout": float(loss_layout.detach()),
            "lr": float(scheduler.get_last_lr()[0]),
        })
        if args.save_every and step % args.save_every == 0 and not args.smoke:
            _save_checkpoint(
                args.output,
                step,
                cfg,
                tower,
                ocr_head,
                mp_head,
                ori_head,
                layout_head,
                optimizer,
                ema,
            )

    logger.close()
    if not args.smoke:
        _save_checkpoint(
            args.output,
            last_step,
            cfg,
            tower,
            ocr_head,
            mp_head,
            ori_head,
            layout_head,
            optimizer,
            ema,
        )
    dt = time.time() - t0
    mode = "real-data" if args.data else "smoke"
    print(f"OMVT SSL {mode} OK in {dt:.1f}s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
